name: 'Meteor Docker'

inputs:
  node-version:
    required: true
    description: 'Node version'
    type: string
  username:
    required: true
  token: 
    required: true


runs:
  using: composite

  steps:
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{inputs.username}}
        password: ${{inputs.token}}

    - name: Unpack build
      shell: bash
      run: |
        mkdir /tmp/build
        cd $_
        curl -Lo Rocket.Chat.tar.gz https://releases.rocket.chat/latest/download
        tar xzf Rocket.Chat.tar.gz
        rm Rocket.Chat.tar.gz

    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
        platforms: linux/amd64,linux/arm64

    - name: Setup NodeJS
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
        cache-modules: true
        install: true

    - run: yarn build
      shell: bash

    - name: Build Docker images
      shell: bash
      run: |
        args=(rocketchat)

        if [[ '${{ inputs.platform }}' = 'alpine' ]]; then
          args+=($SERVICES_PUBLISH)
        fi;

        docker buildx bake -f docker-compose-ci.yml "${args[@]}" --push
