name: 'Meteor Docker'

inputs:
  CR_USER:
    required: true
  CR_PAT:
    required: true
  node-version:
    required: true
    description: 'Node version'
    type: string
  platform:
    required: false
    description: 'Platform'
    type: string

runs:
  using: composite

  steps:
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PAT}}

    - name: Unpack build
      shell: bash
      run: |
        mkdir /tmp/build
        cd $_
        curl -Lo Rocket.Chat.tar.gz https://releases.rocket.chat/latest/download
        tar xzf Rocket.Chat.tar.gz
        rm Rocket.Chat.tar.gz

    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container

    - name: Build Docker images
      shell: bash
      run: |
        args=(rocketchat)

        if [[ '${{ inputs.platform }}' = 'alpine' ]]; then
          args+=($SERVICES_PUBLISH)
        fi;

        docker buildx bake -f docker-compose-ci.yml "${args[@]}" --push
